num=float(input('Digite um numero para ver sua tabuada:'))
print('-'*12)
print('{:.0f}*{}={:.0f}'.format(num,1,num*1))
print('{:.0f}*{}={:.0f}'.format(num,2,num*2))
print('{:.0f}*{}={:.0f}'.format(num,3,num*3))
print('{:.0f}*{}={:.0f}'.format(num,4,num*4))
print('{:.0f}*{}={:.0f}'.format(num,5,num*5))
print('{:.0f}*{}={:.0f}'.format(num,6,num*6))
print('{:.0f}*{}={:.0f}'.format(num,7,num*7))
print('{:.0f}*{}={:.0f}'.format(num,8,num*8))
print('{:.0f}*{}={:.0f}'.format(num,9,num*9))
print('{:.0f}*{}={:.0f}'.format(num,10,num*10))
print('-'*12)